#!/bin/bash

function top_ten_files_large_weight {
    echo "TOP 10 files of maximum size arranged in descending order (path, size and type):"
    for num in {1..10}
    do
        file_line=$(find $1 2>/dev/null -type f -exec du -h {} + | sort -rh | head -10 | sed "${num}q;d")
        if ! [[ -z $file_line ]]
        then
            echo -n "$num - "
            echo -n "$(echo $file_line | awk '{print $2}'), "
            echo -n "$(echo $file_line | awk '{print $1}'), "
            echo "$(echo $file_line | grep -m 1 -o -E "\.[^/.]+$" | awk -F . '{print $2}')"
        fi
    done
}
function top_ten_executables_files {
    echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file)"
    for num in {1..10}
    do
        file_line=$(find $1 2>/dev/null -type f -executable -exec du -h {} + | sort -rh | head -10 | sed "${num}q;d")
        if ! [[ -z $file_line ]]
        then
            echo -n "$num - "
            echo -n "$(echo $file_line | awk '{print $2}'), "
            echo -n "$(echo $file_line | awk '{print $1}'), "
            path=$(echo $file_line | awk '{print $2}')
            MD5=$(md5sum $path | awk '{print $1}')
            echo "$MD5"
        fi
    done
}